### ISSUE TITLE
play: directly play URLs

### ISSUE THREAD

**Issue by zeyla** [dabbotorg/worker#2]
The play command currently searches youtube for results when a URL is provided and uses the first result. We should directly add it to the queue knowing only the URL.

**Comment by Proximyst** [comment]
To add to this, it should be done through a body alike the following (taken from [Lavalink/IMPLEMENTATION.md](https://github.com/Frederikam/Lavalink/blob/master/IMPLEMENTATION.md)):
```json
{
    "op": "play",
    "guildId": "...",
    "track": "https://www.youtube.com/watch?v=dQw4w9WgXcQ", // link goes straight in here
    "startTime": "60000",
    "endTime": "120000"
}
```

As per (all from sedmelluq/lavaplayer):
- [AudioTrackInfo.java lines 27-30](https://github.com/sedmelluq/lavaplayer/blob/master/main/src/main/java/com/sedmelluq/discord/lavaplayer/track/AudioTrackInfo.java#L27-L30)
- [HttpAudioSourceManager lines 143-154](https://github.com/sedmelluq/lavaplayer/blob/master/main/src/main/java/com/sedmelluq/discord/lavaplayer/source/http/HttpAudioSourceManager.java#L143-L154)
- [DefaultAudioPlayerManager line 271](https://github.com/sedmelluq/lavaplayer/blob/master/main/src/main/java/com/sedmelluq/discord/lavaplayer/player/DefaultAudioPlayerManager.java#L271)

**Comment by zeyla** [comment]
Resolved by https://github.com/dabbotorg/worker/commit/467055e8d72ba0c3954b12317382bc87c82ae447.
