### ISSUE TITLE
Dump bugged

### ISSUE THREAD

**Issue by gmantsang** [dabbotorg/worker#23]
The dump command doesn't recognize the Current song as part of the queue.
When you dump with only one song the link gives you an empty list.

**Comment by Proximyst** [comment]
Unsure if this is expected behaviour or not; @TheUnitedStatesOfAmerica might be able to answer?

**Comment by zeyla** [comment]
Closed by https://github.com/dabbotorg/worker/commit/49db1623d7e52b770d0b1cc168632d92156aa1be.
