### ISSUE TITLE
Slow Response and can't clear a "full" queue

### ISSUE THREAD

**Issue by Colink02** [dabbotorg/worker#26]
I've been adding some music but first it likes to freeze the song and then it wont respond when i choose one so i did !!!queue which took a while then showed there were 10 songs. So i tried clearing the queue but  for some reason it wont respond to that either. Not sure what is causing this issue. Seems that its just really slow just retried it and finally worked.

**Comment by TheUnitedStatesOfAmerica** [comment]
@Colink02 This happens because we're maxing out on CPU. We don't have enough patrons to afford bigger servers, it's not a code issue.
